// <auto-generated />
using System;
using DataProcessor.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataProcessor.Service.Migrations
{
    [DbContext(typeof(SensorDataDbContext))]
    partial class SensorDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataProcessor.Service.Models.SensorReading", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("id");

                    b.Property<int?>("Co2")
                        .HasColumnType("integer")
                        .HasColumnName("co2");

                    b.Property<decimal?>("EnergyConsumption")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("energy_consumption");

                    b.Property<int?>("Humidity")
                        .HasColumnType("integer")
                        .HasColumnName("humidity");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<bool?>("MotionDetected")
                        .HasColumnType("boolean")
                        .HasColumnName("motion_detected");

                    b.Property<int?>("Pm25")
                        .HasColumnType("integer")
                        .HasColumnName("pm25");

                    b.Property<string>("SensorId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sensor_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("SensorId")
                        .HasDatabaseName("idx_sensor_readings_sensor_id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("idx_sensor_readings_timestamp");

                    b.HasIndex("Type")
                        .HasDatabaseName("idx_sensor_readings_type");

                    b.ToTable("sensor_readings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
